eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 30
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

services:
  customer-info: http://customer-info-service/info/
  customer-validation: http://customer-validation-service/verify/
